# Generated by Django 4.2 on 2023-04-14 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 28, 16, 46, 35, 425647)),
        ),
    ]
