# Generated by Django 4.2 on 2023-06-23 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 22, 39, 6, 993476), null=True),
        ),
    ]
